// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route/route.proto

package frame.socket.route.proto;

public final class Route {
  private Route() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegisterA2R_ROrBuilder extends
      // @@protoc_insertion_point(interface_extends:route.RegisterA2R_R)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 no = 2;</code>
     */
    int getNo();
  }
  /**
   * <pre>
   * 503001
   * </pre>
   *
   * Protobuf type {@code route.RegisterA2R_R}
   */
  public  static final class RegisterA2R_R extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:route.RegisterA2R_R)
      RegisterA2R_ROrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterA2R_R.newBuilder() to construct.
    private RegisterA2R_R(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterA2R_R() {
      id_ = 0;
      no_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterA2R_R(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              no_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.route.proto.Route.internal_static_route_RegisterA2R_R_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.route.proto.Route.internal_static_route_RegisterA2R_R_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.route.proto.Route.RegisterA2R_R.class, frame.socket.route.proto.Route.RegisterA2R_R.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NO_FIELD_NUMBER = 2;
    private int no_;
    /**
     * <code>int32 no = 2;</code>
     */
    public int getNo() {
      return no_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (no_ != 0) {
        output.writeInt32(2, no_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (no_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, no_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.route.proto.Route.RegisterA2R_R)) {
        return super.equals(obj);
      }
      frame.socket.route.proto.Route.RegisterA2R_R other = (frame.socket.route.proto.Route.RegisterA2R_R) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getNo()
          == other.getNo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NO_FIELD_NUMBER;
      hash = (53 * hash) + getNo();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterA2R_R parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.route.proto.Route.RegisterA2R_R prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 503001
     * </pre>
     *
     * Protobuf type {@code route.RegisterA2R_R}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:route.RegisterA2R_R)
        frame.socket.route.proto.Route.RegisterA2R_ROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterA2R_R_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterA2R_R_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.route.proto.Route.RegisterA2R_R.class, frame.socket.route.proto.Route.RegisterA2R_R.Builder.class);
      }

      // Construct using frame.socket.route.proto.Route.RegisterA2R_R.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        no_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterA2R_R_descriptor;
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterA2R_R getDefaultInstanceForType() {
        return frame.socket.route.proto.Route.RegisterA2R_R.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterA2R_R build() {
        frame.socket.route.proto.Route.RegisterA2R_R result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterA2R_R buildPartial() {
        frame.socket.route.proto.Route.RegisterA2R_R result = new frame.socket.route.proto.Route.RegisterA2R_R(this);
        result.id_ = id_;
        result.no_ = no_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.route.proto.Route.RegisterA2R_R) {
          return mergeFrom((frame.socket.route.proto.Route.RegisterA2R_R)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.route.proto.Route.RegisterA2R_R other) {
        if (other == frame.socket.route.proto.Route.RegisterA2R_R.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getNo() != 0) {
          setNo(other.getNo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.route.proto.Route.RegisterA2R_R parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.route.proto.Route.RegisterA2R_R) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int no_ ;
      /**
       * <code>int32 no = 2;</code>
       */
      public int getNo() {
        return no_;
      }
      /**
       * <code>int32 no = 2;</code>
       */
      public Builder setNo(int value) {
        
        no_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 no = 2;</code>
       */
      public Builder clearNo() {
        
        no_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:route.RegisterA2R_R)
    }

    // @@protoc_insertion_point(class_scope:route.RegisterA2R_R)
    private static final frame.socket.route.proto.Route.RegisterA2R_R DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.route.proto.Route.RegisterA2R_R();
    }

    public static frame.socket.route.proto.Route.RegisterA2R_R getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterA2R_R>
        PARSER = new com.google.protobuf.AbstractParser<RegisterA2R_R>() {
      @java.lang.Override
      public RegisterA2R_R parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterA2R_R(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegisterA2R_R> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterA2R_R> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.route.proto.Route.RegisterA2R_R getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegisterDebugA2R_ROrBuilder extends
      // @@protoc_insertion_point(interface_extends:route.RegisterDebugA2R_R)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     *服务器类型
     * </pre>
     *
     * <code>.common.Server_Type type = 2;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *服务器类型
     * </pre>
     *
     * <code>.common.Server_Type type = 2;</code>
     */
    frame.socket.common.proto.Type.Server_Type getType();

    /**
     * <pre>
     *服务器子类型
     * </pre>
     *
     * <code>int32 sub_type = 3;</code>
     */
    int getSubType();

    /**
     * <pre>
     * 厅主
     * </pre>
     *
     * <code>int32 siteId = 4;</code>
     */
    int getSiteId();
  }
  /**
   * <pre>
   * 503003
   * </pre>
   *
   * Protobuf type {@code route.RegisterDebugA2R_R}
   */
  public  static final class RegisterDebugA2R_R extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:route.RegisterDebugA2R_R)
      RegisterDebugA2R_ROrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterDebugA2R_R.newBuilder() to construct.
    private RegisterDebugA2R_R(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterDebugA2R_R() {
      id_ = 0;
      type_ = 0;
      subType_ = 0;
      siteId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterDebugA2R_R(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {

              subType_ = input.readInt32();
              break;
            }
            case 32: {

              siteId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.route.proto.Route.internal_static_route_RegisterDebugA2R_R_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.route.proto.Route.internal_static_route_RegisterDebugA2R_R_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.route.proto.Route.RegisterDebugA2R_R.class, frame.socket.route.proto.Route.RegisterDebugA2R_R.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 服务器id
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *服务器类型
     * </pre>
     *
     * <code>.common.Server_Type type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *服务器类型
     * </pre>
     *
     * <code>.common.Server_Type type = 2;</code>
     */
    public frame.socket.common.proto.Type.Server_Type getType() {
      @SuppressWarnings("deprecation")
      frame.socket.common.proto.Type.Server_Type result = frame.socket.common.proto.Type.Server_Type.valueOf(type_);
      return result == null ? frame.socket.common.proto.Type.Server_Type.UNRECOGNIZED : result;
    }

    public static final int SUB_TYPE_FIELD_NUMBER = 3;
    private int subType_;
    /**
     * <pre>
     *服务器子类型
     * </pre>
     *
     * <code>int32 sub_type = 3;</code>
     */
    public int getSubType() {
      return subType_;
    }

    public static final int SITEID_FIELD_NUMBER = 4;
    private int siteId_;
    /**
     * <pre>
     * 厅主
     * </pre>
     *
     * <code>int32 siteId = 4;</code>
     */
    public int getSiteId() {
      return siteId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (type_ != frame.socket.common.proto.Type.Server_Type.SERVER_TYPE_GATE.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (subType_ != 0) {
        output.writeInt32(3, subType_);
      }
      if (siteId_ != 0) {
        output.writeInt32(4, siteId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (type_ != frame.socket.common.proto.Type.Server_Type.SERVER_TYPE_GATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (subType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, subType_);
      }
      if (siteId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, siteId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.route.proto.Route.RegisterDebugA2R_R)) {
        return super.equals(obj);
      }
      frame.socket.route.proto.Route.RegisterDebugA2R_R other = (frame.socket.route.proto.Route.RegisterDebugA2R_R) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && type_ == other.type_;
      result = result && (getSubType()
          == other.getSubType());
      result = result && (getSiteId()
          == other.getSiteId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SUB_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSubType();
      hash = (37 * hash) + SITEID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterDebugA2R_R parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.route.proto.Route.RegisterDebugA2R_R prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 503003
     * </pre>
     *
     * Protobuf type {@code route.RegisterDebugA2R_R}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:route.RegisterDebugA2R_R)
        frame.socket.route.proto.Route.RegisterDebugA2R_ROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterDebugA2R_R_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterDebugA2R_R_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.route.proto.Route.RegisterDebugA2R_R.class, frame.socket.route.proto.Route.RegisterDebugA2R_R.Builder.class);
      }

      // Construct using frame.socket.route.proto.Route.RegisterDebugA2R_R.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        type_ = 0;

        subType_ = 0;

        siteId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterDebugA2R_R_descriptor;
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterDebugA2R_R getDefaultInstanceForType() {
        return frame.socket.route.proto.Route.RegisterDebugA2R_R.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterDebugA2R_R build() {
        frame.socket.route.proto.Route.RegisterDebugA2R_R result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterDebugA2R_R buildPartial() {
        frame.socket.route.proto.Route.RegisterDebugA2R_R result = new frame.socket.route.proto.Route.RegisterDebugA2R_R(this);
        result.id_ = id_;
        result.type_ = type_;
        result.subType_ = subType_;
        result.siteId_ = siteId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.route.proto.Route.RegisterDebugA2R_R) {
          return mergeFrom((frame.socket.route.proto.Route.RegisterDebugA2R_R)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.route.proto.Route.RegisterDebugA2R_R other) {
        if (other == frame.socket.route.proto.Route.RegisterDebugA2R_R.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSubType() != 0) {
          setSubType(other.getSubType());
        }
        if (other.getSiteId() != 0) {
          setSiteId(other.getSiteId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.route.proto.Route.RegisterDebugA2R_R parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.route.proto.Route.RegisterDebugA2R_R) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器id
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *服务器类型
       * </pre>
       *
       * <code>.common.Server_Type type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *服务器类型
       * </pre>
       *
       * <code>.common.Server_Type type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器类型
       * </pre>
       *
       * <code>.common.Server_Type type = 2;</code>
       */
      public frame.socket.common.proto.Type.Server_Type getType() {
        @SuppressWarnings("deprecation")
        frame.socket.common.proto.Type.Server_Type result = frame.socket.common.proto.Type.Server_Type.valueOf(type_);
        return result == null ? frame.socket.common.proto.Type.Server_Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *服务器类型
       * </pre>
       *
       * <code>.common.Server_Type type = 2;</code>
       */
      public Builder setType(frame.socket.common.proto.Type.Server_Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器类型
       * </pre>
       *
       * <code>.common.Server_Type type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int subType_ ;
      /**
       * <pre>
       *服务器子类型
       * </pre>
       *
       * <code>int32 sub_type = 3;</code>
       */
      public int getSubType() {
        return subType_;
      }
      /**
       * <pre>
       *服务器子类型
       * </pre>
       *
       * <code>int32 sub_type = 3;</code>
       */
      public Builder setSubType(int value) {
        
        subType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器子类型
       * </pre>
       *
       * <code>int32 sub_type = 3;</code>
       */
      public Builder clearSubType() {
        
        subType_ = 0;
        onChanged();
        return this;
      }

      private int siteId_ ;
      /**
       * <pre>
       * 厅主
       * </pre>
       *
       * <code>int32 siteId = 4;</code>
       */
      public int getSiteId() {
        return siteId_;
      }
      /**
       * <pre>
       * 厅主
       * </pre>
       *
       * <code>int32 siteId = 4;</code>
       */
      public Builder setSiteId(int value) {
        
        siteId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 厅主
       * </pre>
       *
       * <code>int32 siteId = 4;</code>
       */
      public Builder clearSiteId() {
        
        siteId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:route.RegisterDebugA2R_R)
    }

    // @@protoc_insertion_point(class_scope:route.RegisterDebugA2R_R)
    private static final frame.socket.route.proto.Route.RegisterDebugA2R_R DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.route.proto.Route.RegisterDebugA2R_R();
    }

    public static frame.socket.route.proto.Route.RegisterDebugA2R_R getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterDebugA2R_R>
        PARSER = new com.google.protobuf.AbstractParser<RegisterDebugA2R_R>() {
      @java.lang.Override
      public RegisterDebugA2R_R parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterDebugA2R_R(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegisterDebugA2R_R> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterDebugA2R_R> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.route.proto.Route.RegisterDebugA2R_R getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegisterR2A_SOrBuilder extends
      // @@protoc_insertion_point(interface_extends:route.RegisterR2A_S)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 503002
   * </pre>
   *
   * Protobuf type {@code route.RegisterR2A_S}
   */
  public  static final class RegisterR2A_S extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:route.RegisterR2A_S)
      RegisterR2A_SOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisterR2A_S.newBuilder() to construct.
    private RegisterR2A_S(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisterR2A_S() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegisterR2A_S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.route.proto.Route.internal_static_route_RegisterR2A_S_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.route.proto.Route.internal_static_route_RegisterR2A_S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.route.proto.Route.RegisterR2A_S.class, frame.socket.route.proto.Route.RegisterR2A_S.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.route.proto.Route.RegisterR2A_S)) {
        return super.equals(obj);
      }
      frame.socket.route.proto.Route.RegisterR2A_S other = (frame.socket.route.proto.Route.RegisterR2A_S) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.route.proto.Route.RegisterR2A_S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.route.proto.Route.RegisterR2A_S prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 503002
     * </pre>
     *
     * Protobuf type {@code route.RegisterR2A_S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:route.RegisterR2A_S)
        frame.socket.route.proto.Route.RegisterR2A_SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterR2A_S_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterR2A_S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.route.proto.Route.RegisterR2A_S.class, frame.socket.route.proto.Route.RegisterR2A_S.Builder.class);
      }

      // Construct using frame.socket.route.proto.Route.RegisterR2A_S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.route.proto.Route.internal_static_route_RegisterR2A_S_descriptor;
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterR2A_S getDefaultInstanceForType() {
        return frame.socket.route.proto.Route.RegisterR2A_S.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterR2A_S build() {
        frame.socket.route.proto.Route.RegisterR2A_S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.route.proto.Route.RegisterR2A_S buildPartial() {
        frame.socket.route.proto.Route.RegisterR2A_S result = new frame.socket.route.proto.Route.RegisterR2A_S(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.route.proto.Route.RegisterR2A_S) {
          return mergeFrom((frame.socket.route.proto.Route.RegisterR2A_S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.route.proto.Route.RegisterR2A_S other) {
        if (other == frame.socket.route.proto.Route.RegisterR2A_S.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.route.proto.Route.RegisterR2A_S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.route.proto.Route.RegisterR2A_S) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:route.RegisterR2A_S)
    }

    // @@protoc_insertion_point(class_scope:route.RegisterR2A_S)
    private static final frame.socket.route.proto.Route.RegisterR2A_S DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.route.proto.Route.RegisterR2A_S();
    }

    public static frame.socket.route.proto.Route.RegisterR2A_S getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterR2A_S>
        PARSER = new com.google.protobuf.AbstractParser<RegisterR2A_S>() {
      @java.lang.Override
      public RegisterR2A_S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterR2A_S(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegisterR2A_S> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterR2A_S> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.route.proto.Route.RegisterR2A_S getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_route_RegisterA2R_R_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_route_RegisterA2R_R_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_route_RegisterDebugA2R_R_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_route_RegisterDebugA2R_R_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_route_RegisterR2A_S_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_route_RegisterR2A_S_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021route/route.proto\022\005route\032\021common/type." +
      "proto\"\'\n\rRegisterA2R_R\022\n\n\002id\030\001 \001(\005\022\n\n\002no" +
      "\030\002 \001(\005\"e\n\022RegisterDebugA2R_R\022\n\n\002id\030\001 \001(\005" +
      "\022!\n\004type\030\002 \001(\0162\023.common.Server_Type\022\020\n\010s" +
      "ub_type\030\003 \001(\005\022\016\n\006siteId\030\004 \001(\005\"\017\n\rRegiste" +
      "rR2A_SB\035\n\030frame.socket.route.proto\370\001\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          frame.socket.common.proto.Type.getDescriptor(),
        }, assigner);
    internal_static_route_RegisterA2R_R_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_route_RegisterA2R_R_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_route_RegisterA2R_R_descriptor,
        new java.lang.String[] { "Id", "No", });
    internal_static_route_RegisterDebugA2R_R_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_route_RegisterDebugA2R_R_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_route_RegisterDebugA2R_R_descriptor,
        new java.lang.String[] { "Id", "Type", "SubType", "SiteId", });
    internal_static_route_RegisterR2A_S_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_route_RegisterR2A_S_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_route_RegisterR2A_S_descriptor,
        new java.lang.String[] { });
    frame.socket.common.proto.Type.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
