package frame.socket.common.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameHistory.proto

public final class GameHistory {
  private GameHistory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResHistorysOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResHistorys)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pageIndex = 1;</code>
     */
    int getPageIndex();

    /**
     * <code>int32 pageMax = 2;</code>
     */
    int getPageMax();

    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    java.util.List<GameHistory.ResHistorys.gameHistory> 
        getGamesList();
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    GameHistory.ResHistorys.gameHistory getGames(int index);
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    int getGamesCount();
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    java.util.List<? extends GameHistory.ResHistorys.gameHistoryOrBuilder> 
        getGamesOrBuilderList();
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    GameHistory.ResHistorys.gameHistoryOrBuilder getGamesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResHistorys}
   */
  public  static final class ResHistorys extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResHistorys)
      ResHistorysOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResHistorys.newBuilder() to construct.
    private ResHistorys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResHistorys() {
      pageIndex_ = 0;
      pageMax_ = 0;
      games_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResHistorys(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pageIndex_ = input.readInt32();
              break;
            }
            case 16: {

              pageMax_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                games_ = new java.util.ArrayList<GameHistory.ResHistorys.gameHistory>();
                mutable_bitField0_ |= 0x00000004;
              }
              games_.add(
                  input.readMessage(GameHistory.ResHistorys.gameHistory.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          games_ = java.util.Collections.unmodifiableList(games_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameHistory.internal_static_ResHistorys_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameHistory.internal_static_ResHistorys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameHistory.ResHistorys.class, GameHistory.ResHistorys.Builder.class);
    }

    public interface gameHistoryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ResHistorys.gameHistory)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>fixed64 endTime = 1;</code>
       */
      long getEndTime();

      /**
       * <pre>
       *我的输赢
       * </pre>
       *
       * <code>int64 win = 2;</code>
       */
      long getWin();

      /**
       * <code>string roomName = 3;</code>
       */
      java.lang.String getRoomName();
      /**
       * <code>string roomName = 3;</code>
       */
      com.google.protobuf.ByteString
          getRoomNameBytes();

      /**
       * <code>string gameId = 4;</code>
       */
      java.lang.String getGameId();
      /**
       * <code>string gameId = 4;</code>
       */
      com.google.protobuf.ByteString
          getGameIdBytes();
    }
    /**
     * Protobuf type {@code ResHistorys.gameHistory}
     */
    public  static final class gameHistory extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ResHistorys.gameHistory)
        gameHistoryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use gameHistory.newBuilder() to construct.
      private gameHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private gameHistory() {
        endTime_ = 0L;
        win_ = 0L;
        roomName_ = "";
        gameId_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private gameHistory(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {

                endTime_ = input.readFixed64();
                break;
              }
              case 16: {

                win_ = input.readInt64();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                roomName_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                gameId_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameHistory.internal_static_ResHistorys_gameHistory_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameHistory.internal_static_ResHistorys_gameHistory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameHistory.ResHistorys.gameHistory.class, GameHistory.ResHistorys.gameHistory.Builder.class);
      }

      public static final int ENDTIME_FIELD_NUMBER = 1;
      private long endTime_;
      /**
       * <code>fixed64 endTime = 1;</code>
       */
      public long getEndTime() {
        return endTime_;
      }

      public static final int WIN_FIELD_NUMBER = 2;
      private long win_;
      /**
       * <pre>
       *我的输赢
       * </pre>
       *
       * <code>int64 win = 2;</code>
       */
      public long getWin() {
        return win_;
      }

      public static final int ROOMNAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object roomName_;
      /**
       * <code>string roomName = 3;</code>
       */
      public java.lang.String getRoomName() {
        java.lang.Object ref = roomName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomName_ = s;
          return s;
        }
      }
      /**
       * <code>string roomName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        java.lang.Object ref = roomName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int GAMEID_FIELD_NUMBER = 4;
      private volatile java.lang.Object gameId_;
      /**
       * <code>string gameId = 4;</code>
       */
      public java.lang.String getGameId() {
        java.lang.Object ref = gameId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gameId_ = s;
          return s;
        }
      }
      /**
       * <code>string gameId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGameIdBytes() {
        java.lang.Object ref = gameId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (endTime_ != 0L) {
          output.writeFixed64(1, endTime_);
        }
        if (win_ != 0L) {
          output.writeInt64(2, win_);
        }
        if (!getRoomNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roomName_);
        }
        if (!getGameIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gameId_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (endTime_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeFixed64Size(1, endTime_);
        }
        if (win_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, win_);
        }
        if (!getRoomNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roomName_);
        }
        if (!getGameIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gameId_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof GameHistory.ResHistorys.gameHistory)) {
          return super.equals(obj);
        }
        GameHistory.ResHistorys.gameHistory other = (GameHistory.ResHistorys.gameHistory) obj;

        boolean result = true;
        result = result && (getEndTime()
            == other.getEndTime());
        result = result && (getWin()
            == other.getWin());
        result = result && getRoomName()
            .equals(other.getRoomName());
        result = result && getGameId()
            .equals(other.getGameId());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEndTime());
        hash = (37 * hash) + WIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getWin());
        hash = (37 * hash) + ROOMNAME_FIELD_NUMBER;
        hash = (53 * hash) + getRoomName().hashCode();
        hash = (37 * hash) + GAMEID_FIELD_NUMBER;
        hash = (53 * hash) + getGameId().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static GameHistory.ResHistorys.gameHistory parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static GameHistory.ResHistorys.gameHistory parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static GameHistory.ResHistorys.gameHistory parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static GameHistory.ResHistorys.gameHistory parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(GameHistory.ResHistorys.gameHistory prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ResHistorys.gameHistory}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ResHistorys.gameHistory)
          GameHistory.ResHistorys.gameHistoryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return GameHistory.internal_static_ResHistorys_gameHistory_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return GameHistory.internal_static_ResHistorys_gameHistory_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  GameHistory.ResHistorys.gameHistory.class, GameHistory.ResHistorys.gameHistory.Builder.class);
        }

        // Construct using GameHistory.ResHistorys.gameHistory.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          endTime_ = 0L;

          win_ = 0L;

          roomName_ = "";

          gameId_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return GameHistory.internal_static_ResHistorys_gameHistory_descriptor;
        }

        @java.lang.Override
        public GameHistory.ResHistorys.gameHistory getDefaultInstanceForType() {
          return GameHistory.ResHistorys.gameHistory.getDefaultInstance();
        }

        @java.lang.Override
        public GameHistory.ResHistorys.gameHistory build() {
          GameHistory.ResHistorys.gameHistory result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public GameHistory.ResHistorys.gameHistory buildPartial() {
          GameHistory.ResHistorys.gameHistory result = new GameHistory.ResHistorys.gameHistory(this);
          result.endTime_ = endTime_;
          result.win_ = win_;
          result.roomName_ = roomName_;
          result.gameId_ = gameId_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof GameHistory.ResHistorys.gameHistory) {
            return mergeFrom((GameHistory.ResHistorys.gameHistory)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(GameHistory.ResHistorys.gameHistory other) {
          if (other == GameHistory.ResHistorys.gameHistory.getDefaultInstance()) return this;
          if (other.getEndTime() != 0L) {
            setEndTime(other.getEndTime());
          }
          if (other.getWin() != 0L) {
            setWin(other.getWin());
          }
          if (!other.getRoomName().isEmpty()) {
            roomName_ = other.roomName_;
            onChanged();
          }
          if (!other.getGameId().isEmpty()) {
            gameId_ = other.gameId_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          GameHistory.ResHistorys.gameHistory parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (GameHistory.ResHistorys.gameHistory) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long endTime_ ;
        /**
         * <code>fixed64 endTime = 1;</code>
         */
        public long getEndTime() {
          return endTime_;
        }
        /**
         * <code>fixed64 endTime = 1;</code>
         */
        public Builder setEndTime(long value) {
          
          endTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>fixed64 endTime = 1;</code>
         */
        public Builder clearEndTime() {
          
          endTime_ = 0L;
          onChanged();
          return this;
        }

        private long win_ ;
        /**
         * <pre>
         *我的输赢
         * </pre>
         *
         * <code>int64 win = 2;</code>
         */
        public long getWin() {
          return win_;
        }
        /**
         * <pre>
         *我的输赢
         * </pre>
         *
         * <code>int64 win = 2;</code>
         */
        public Builder setWin(long value) {
          
          win_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *我的输赢
         * </pre>
         *
         * <code>int64 win = 2;</code>
         */
        public Builder clearWin() {
          
          win_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object roomName_ = "";
        /**
         * <code>string roomName = 3;</code>
         */
        public java.lang.String getRoomName() {
          java.lang.Object ref = roomName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            roomName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string roomName = 3;</code>
         */
        public com.google.protobuf.ByteString
            getRoomNameBytes() {
          java.lang.Object ref = roomName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            roomName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string roomName = 3;</code>
         */
        public Builder setRoomName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          roomName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string roomName = 3;</code>
         */
        public Builder clearRoomName() {
          
          roomName_ = getDefaultInstance().getRoomName();
          onChanged();
          return this;
        }
        /**
         * <code>string roomName = 3;</code>
         */
        public Builder setRoomNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          roomName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object gameId_ = "";
        /**
         * <code>string gameId = 4;</code>
         */
        public java.lang.String getGameId() {
          java.lang.Object ref = gameId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            gameId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string gameId = 4;</code>
         */
        public com.google.protobuf.ByteString
            getGameIdBytes() {
          java.lang.Object ref = gameId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            gameId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string gameId = 4;</code>
         */
        public Builder setGameId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          gameId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string gameId = 4;</code>
         */
        public Builder clearGameId() {
          
          gameId_ = getDefaultInstance().getGameId();
          onChanged();
          return this;
        }
        /**
         * <code>string gameId = 4;</code>
         */
        public Builder setGameIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          gameId_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ResHistorys.gameHistory)
      }

      // @@protoc_insertion_point(class_scope:ResHistorys.gameHistory)
      private static final GameHistory.ResHistorys.gameHistory DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new GameHistory.ResHistorys.gameHistory();
      }

      public static GameHistory.ResHistorys.gameHistory getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<gameHistory>
          PARSER = new com.google.protobuf.AbstractParser<gameHistory>() {
        @java.lang.Override
        public gameHistory parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new gameHistory(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<gameHistory> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<gameHistory> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public GameHistory.ResHistorys.gameHistory getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int PAGEINDEX_FIELD_NUMBER = 1;
    private int pageIndex_;
    /**
     * <code>int32 pageIndex = 1;</code>
     */
    public int getPageIndex() {
      return pageIndex_;
    }

    public static final int PAGEMAX_FIELD_NUMBER = 2;
    private int pageMax_;
    /**
     * <code>int32 pageMax = 2;</code>
     */
    public int getPageMax() {
      return pageMax_;
    }

    public static final int GAMES_FIELD_NUMBER = 3;
    private java.util.List<GameHistory.ResHistorys.gameHistory> games_;
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    public java.util.List<GameHistory.ResHistorys.gameHistory> getGamesList() {
      return games_;
    }
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    public java.util.List<? extends GameHistory.ResHistorys.gameHistoryOrBuilder> 
        getGamesOrBuilderList() {
      return games_;
    }
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    public int getGamesCount() {
      return games_.size();
    }
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    public GameHistory.ResHistorys.gameHistory getGames(int index) {
      return games_.get(index);
    }
    /**
     * <code>repeated .ResHistorys.gameHistory games = 3;</code>
     */
    public GameHistory.ResHistorys.gameHistoryOrBuilder getGamesOrBuilder(
        int index) {
      return games_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageIndex_ != 0) {
        output.writeInt32(1, pageIndex_);
      }
      if (pageMax_ != 0) {
        output.writeInt32(2, pageMax_);
      }
      for (int i = 0; i < games_.size(); i++) {
        output.writeMessage(3, games_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageIndex_);
      }
      if (pageMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageMax_);
      }
      for (int i = 0; i < games_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, games_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GameHistory.ResHistorys)) {
        return super.equals(obj);
      }
      GameHistory.ResHistorys other = (GameHistory.ResHistorys) obj;

      boolean result = true;
      result = result && (getPageIndex()
          == other.getPageIndex());
      result = result && (getPageMax()
          == other.getPageMax());
      result = result && getGamesList()
          .equals(other.getGamesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGEINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getPageIndex();
      hash = (37 * hash) + PAGEMAX_FIELD_NUMBER;
      hash = (53 * hash) + getPageMax();
      if (getGamesCount() > 0) {
        hash = (37 * hash) + GAMES_FIELD_NUMBER;
        hash = (53 * hash) + getGamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GameHistory.ResHistorys parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameHistory.ResHistorys parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameHistory.ResHistorys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameHistory.ResHistorys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameHistory.ResHistorys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameHistory.ResHistorys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameHistory.ResHistorys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameHistory.ResHistorys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameHistory.ResHistorys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GameHistory.ResHistorys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameHistory.ResHistorys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameHistory.ResHistorys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GameHistory.ResHistorys prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResHistorys}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResHistorys)
        GameHistory.ResHistorysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameHistory.internal_static_ResHistorys_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameHistory.internal_static_ResHistorys_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameHistory.ResHistorys.class, GameHistory.ResHistorys.Builder.class);
      }

      // Construct using GameHistory.ResHistorys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGamesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pageIndex_ = 0;

        pageMax_ = 0;

        if (gamesBuilder_ == null) {
          games_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          gamesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameHistory.internal_static_ResHistorys_descriptor;
      }

      @java.lang.Override
      public GameHistory.ResHistorys getDefaultInstanceForType() {
        return GameHistory.ResHistorys.getDefaultInstance();
      }

      @java.lang.Override
      public GameHistory.ResHistorys build() {
        GameHistory.ResHistorys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GameHistory.ResHistorys buildPartial() {
        GameHistory.ResHistorys result = new GameHistory.ResHistorys(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.pageIndex_ = pageIndex_;
        result.pageMax_ = pageMax_;
        if (gamesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            games_ = java.util.Collections.unmodifiableList(games_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.games_ = games_;
        } else {
          result.games_ = gamesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameHistory.ResHistorys) {
          return mergeFrom((GameHistory.ResHistorys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameHistory.ResHistorys other) {
        if (other == GameHistory.ResHistorys.getDefaultInstance()) return this;
        if (other.getPageIndex() != 0) {
          setPageIndex(other.getPageIndex());
        }
        if (other.getPageMax() != 0) {
          setPageMax(other.getPageMax());
        }
        if (gamesBuilder_ == null) {
          if (!other.games_.isEmpty()) {
            if (games_.isEmpty()) {
              games_ = other.games_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureGamesIsMutable();
              games_.addAll(other.games_);
            }
            onChanged();
          }
        } else {
          if (!other.games_.isEmpty()) {
            if (gamesBuilder_.isEmpty()) {
              gamesBuilder_.dispose();
              gamesBuilder_ = null;
              games_ = other.games_;
              bitField0_ = (bitField0_ & ~0x00000004);
              gamesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGamesFieldBuilder() : null;
            } else {
              gamesBuilder_.addAllMessages(other.games_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameHistory.ResHistorys parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameHistory.ResHistorys) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pageIndex_ ;
      /**
       * <code>int32 pageIndex = 1;</code>
       */
      public int getPageIndex() {
        return pageIndex_;
      }
      /**
       * <code>int32 pageIndex = 1;</code>
       */
      public Builder setPageIndex(int value) {
        
        pageIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pageIndex = 1;</code>
       */
      public Builder clearPageIndex() {
        
        pageIndex_ = 0;
        onChanged();
        return this;
      }

      private int pageMax_ ;
      /**
       * <code>int32 pageMax = 2;</code>
       */
      public int getPageMax() {
        return pageMax_;
      }
      /**
       * <code>int32 pageMax = 2;</code>
       */
      public Builder setPageMax(int value) {
        
        pageMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pageMax = 2;</code>
       */
      public Builder clearPageMax() {
        
        pageMax_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<GameHistory.ResHistorys.gameHistory> games_ =
        java.util.Collections.emptyList();
      private void ensureGamesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          games_ = new java.util.ArrayList<GameHistory.ResHistorys.gameHistory>(games_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GameHistory.ResHistorys.gameHistory, GameHistory.ResHistorys.gameHistory.Builder, GameHistory.ResHistorys.gameHistoryOrBuilder> gamesBuilder_;

      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public java.util.List<GameHistory.ResHistorys.gameHistory> getGamesList() {
        if (gamesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(games_);
        } else {
          return gamesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public int getGamesCount() {
        if (gamesBuilder_ == null) {
          return games_.size();
        } else {
          return gamesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public GameHistory.ResHistorys.gameHistory getGames(int index) {
        if (gamesBuilder_ == null) {
          return games_.get(index);
        } else {
          return gamesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder setGames(
          int index, GameHistory.ResHistorys.gameHistory value) {
        if (gamesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGamesIsMutable();
          games_.set(index, value);
          onChanged();
        } else {
          gamesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder setGames(
          int index, GameHistory.ResHistorys.gameHistory.Builder builderForValue) {
        if (gamesBuilder_ == null) {
          ensureGamesIsMutable();
          games_.set(index, builderForValue.build());
          onChanged();
        } else {
          gamesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder addGames(GameHistory.ResHistorys.gameHistory value) {
        if (gamesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGamesIsMutable();
          games_.add(value);
          onChanged();
        } else {
          gamesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder addGames(
          int index, GameHistory.ResHistorys.gameHistory value) {
        if (gamesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGamesIsMutable();
          games_.add(index, value);
          onChanged();
        } else {
          gamesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder addGames(
          GameHistory.ResHistorys.gameHistory.Builder builderForValue) {
        if (gamesBuilder_ == null) {
          ensureGamesIsMutable();
          games_.add(builderForValue.build());
          onChanged();
        } else {
          gamesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder addGames(
          int index, GameHistory.ResHistorys.gameHistory.Builder builderForValue) {
        if (gamesBuilder_ == null) {
          ensureGamesIsMutable();
          games_.add(index, builderForValue.build());
          onChanged();
        } else {
          gamesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder addAllGames(
          java.lang.Iterable<? extends GameHistory.ResHistorys.gameHistory> values) {
        if (gamesBuilder_ == null) {
          ensureGamesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, games_);
          onChanged();
        } else {
          gamesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder clearGames() {
        if (gamesBuilder_ == null) {
          games_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          gamesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public Builder removeGames(int index) {
        if (gamesBuilder_ == null) {
          ensureGamesIsMutable();
          games_.remove(index);
          onChanged();
        } else {
          gamesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public GameHistory.ResHistorys.gameHistory.Builder getGamesBuilder(
          int index) {
        return getGamesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public GameHistory.ResHistorys.gameHistoryOrBuilder getGamesOrBuilder(
          int index) {
        if (gamesBuilder_ == null) {
          return games_.get(index);  } else {
          return gamesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public java.util.List<? extends GameHistory.ResHistorys.gameHistoryOrBuilder> 
           getGamesOrBuilderList() {
        if (gamesBuilder_ != null) {
          return gamesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(games_);
        }
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public GameHistory.ResHistorys.gameHistory.Builder addGamesBuilder() {
        return getGamesFieldBuilder().addBuilder(
            GameHistory.ResHistorys.gameHistory.getDefaultInstance());
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public GameHistory.ResHistorys.gameHistory.Builder addGamesBuilder(
          int index) {
        return getGamesFieldBuilder().addBuilder(
            index, GameHistory.ResHistorys.gameHistory.getDefaultInstance());
      }
      /**
       * <code>repeated .ResHistorys.gameHistory games = 3;</code>
       */
      public java.util.List<GameHistory.ResHistorys.gameHistory.Builder> 
           getGamesBuilderList() {
        return getGamesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GameHistory.ResHistorys.gameHistory, GameHistory.ResHistorys.gameHistory.Builder, GameHistory.ResHistorys.gameHistoryOrBuilder> 
          getGamesFieldBuilder() {
        if (gamesBuilder_ == null) {
          gamesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GameHistory.ResHistorys.gameHistory, GameHistory.ResHistorys.gameHistory.Builder, GameHistory.ResHistorys.gameHistoryOrBuilder>(
                  games_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          games_ = null;
        }
        return gamesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResHistorys)
    }

    // @@protoc_insertion_point(class_scope:ResHistorys)
    private static final GameHistory.ResHistorys DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GameHistory.ResHistorys();
    }

    public static GameHistory.ResHistorys getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResHistorys>
        PARSER = new com.google.protobuf.AbstractParser<ResHistorys>() {
      @java.lang.Override
      public ResHistorys parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResHistorys(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResHistorys> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResHistorys> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GameHistory.ResHistorys getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqHistorysOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqHistorys)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pageSize = 1;</code>
     */
    int getPageSize();

    /**
     * <code>int32 pageIndex = 2;</code>
     */
    int getPageIndex();
  }
  /**
   * Protobuf type {@code ReqHistorys}
   */
  public  static final class ReqHistorys extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReqHistorys)
      ReqHistorysOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqHistorys.newBuilder() to construct.
    private ReqHistorys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqHistorys() {
      pageSize_ = 0;
      pageIndex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqHistorys(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pageSize_ = input.readInt32();
              break;
            }
            case 16: {

              pageIndex_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GameHistory.internal_static_ReqHistorys_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GameHistory.internal_static_ReqHistorys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameHistory.ReqHistorys.class, GameHistory.ReqHistorys.Builder.class);
    }

    public static final int PAGESIZE_FIELD_NUMBER = 1;
    private int pageSize_;
    /**
     * <code>int32 pageSize = 1;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    public static final int PAGEINDEX_FIELD_NUMBER = 2;
    private int pageIndex_;
    /**
     * <code>int32 pageIndex = 2;</code>
     */
    public int getPageIndex() {
      return pageIndex_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageSize_ != 0) {
        output.writeInt32(1, pageSize_);
      }
      if (pageIndex_ != 0) {
        output.writeInt32(2, pageIndex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageSize_);
      }
      if (pageIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GameHistory.ReqHistorys)) {
        return super.equals(obj);
      }
      GameHistory.ReqHistorys other = (GameHistory.ReqHistorys) obj;

      boolean result = true;
      result = result && (getPageSize()
          == other.getPageSize());
      result = result && (getPageIndex()
          == other.getPageIndex());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + PAGEINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getPageIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GameHistory.ReqHistorys parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameHistory.ReqHistorys parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameHistory.ReqHistorys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameHistory.ReqHistorys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameHistory.ReqHistorys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameHistory.ReqHistorys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameHistory.ReqHistorys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameHistory.ReqHistorys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameHistory.ReqHistorys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GameHistory.ReqHistorys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameHistory.ReqHistorys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameHistory.ReqHistorys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GameHistory.ReqHistorys prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqHistorys}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqHistorys)
        GameHistory.ReqHistorysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GameHistory.internal_static_ReqHistorys_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GameHistory.internal_static_ReqHistorys_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameHistory.ReqHistorys.class, GameHistory.ReqHistorys.Builder.class);
      }

      // Construct using GameHistory.ReqHistorys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pageSize_ = 0;

        pageIndex_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GameHistory.internal_static_ReqHistorys_descriptor;
      }

      @java.lang.Override
      public GameHistory.ReqHistorys getDefaultInstanceForType() {
        return GameHistory.ReqHistorys.getDefaultInstance();
      }

      @java.lang.Override
      public GameHistory.ReqHistorys build() {
        GameHistory.ReqHistorys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GameHistory.ReqHistorys buildPartial() {
        GameHistory.ReqHistorys result = new GameHistory.ReqHistorys(this);
        result.pageSize_ = pageSize_;
        result.pageIndex_ = pageIndex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameHistory.ReqHistorys) {
          return mergeFrom((GameHistory.ReqHistorys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameHistory.ReqHistorys other) {
        if (other == GameHistory.ReqHistorys.getDefaultInstance()) return this;
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getPageIndex() != 0) {
          setPageIndex(other.getPageIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GameHistory.ReqHistorys parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GameHistory.ReqHistorys) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pageSize_ ;
      /**
       * <code>int32 pageSize = 1;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>int32 pageSize = 1;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pageSize = 1;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private int pageIndex_ ;
      /**
       * <code>int32 pageIndex = 2;</code>
       */
      public int getPageIndex() {
        return pageIndex_;
      }
      /**
       * <code>int32 pageIndex = 2;</code>
       */
      public Builder setPageIndex(int value) {
        
        pageIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pageIndex = 2;</code>
       */
      public Builder clearPageIndex() {
        
        pageIndex_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReqHistorys)
    }

    // @@protoc_insertion_point(class_scope:ReqHistorys)
    private static final GameHistory.ReqHistorys DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GameHistory.ReqHistorys();
    }

    public static GameHistory.ReqHistorys getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqHistorys>
        PARSER = new com.google.protobuf.AbstractParser<ReqHistorys>() {
      @java.lang.Override
      public ReqHistorys parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqHistorys(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqHistorys> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqHistorys> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GameHistory.ReqHistorys getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResHistorys_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResHistorys_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResHistorys_gameHistory_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResHistorys_gameHistory_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqHistorys_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReqHistorys_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gameHistory.proto\"\251\001\n\013ResHistorys\022\021\n\tp" +
      "ageIndex\030\001 \001(\005\022\017\n\007pageMax\030\002 \001(\005\022\'\n\005games" +
      "\030\003 \003(\0132\030.ResHistorys.gameHistory\032M\n\013game" +
      "History\022\017\n\007endTime\030\001 \001(\006\022\013\n\003win\030\002 \001(\003\022\020\n" +
      "\010roomName\030\003 \001(\t\022\016\n\006gameId\030\004 \001(\t\"2\n\013ReqHi" +
      "storys\022\020\n\010pageSize\030\001 \001(\005\022\021\n\tpageIndex\030\002 " +
      "\001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ResHistorys_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResHistorys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResHistorys_descriptor,
        new java.lang.String[] { "PageIndex", "PageMax", "Games", });
    internal_static_ResHistorys_gameHistory_descriptor =
      internal_static_ResHistorys_descriptor.getNestedTypes().get(0);
    internal_static_ResHistorys_gameHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResHistorys_gameHistory_descriptor,
        new java.lang.String[] { "EndTime", "Win", "RoomName", "GameId", });
    internal_static_ReqHistorys_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReqHistorys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReqHistorys_descriptor,
        new java.lang.String[] { "PageSize", "PageIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
