// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game/playerControl.proto

package frame.socket.common.proto;

public final class PlayerControl {
  private PlayerControl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ControlReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.ControlReq)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *玩家单控协议  //获取实时输赢
   * 600601 (后台查游戏DB实时输赢)
   * </pre>
   *
   * Protobuf type {@code game.ControlReq}
   */
  public  static final class ControlReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.ControlReq)
      ControlReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControlReq.newBuilder() to construct.
    private ControlReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControlReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_ControlReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_ControlReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.common.proto.PlayerControl.ControlReq.class, frame.socket.common.proto.PlayerControl.ControlReq.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.common.proto.PlayerControl.ControlReq)) {
        return super.equals(obj);
      }
      frame.socket.common.proto.PlayerControl.ControlReq other = (frame.socket.common.proto.PlayerControl.ControlReq) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.ControlReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.common.proto.PlayerControl.ControlReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *玩家单控协议  //获取实时输赢
     * 600601 (后台查游戏DB实时输赢)
     * </pre>
     *
     * Protobuf type {@code game.ControlReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.ControlReq)
        frame.socket.common.proto.PlayerControl.ControlReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_ControlReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_ControlReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.common.proto.PlayerControl.ControlReq.class, frame.socket.common.proto.PlayerControl.ControlReq.Builder.class);
      }

      // Construct using frame.socket.common.proto.PlayerControl.ControlReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_ControlReq_descriptor;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.ControlReq getDefaultInstanceForType() {
        return frame.socket.common.proto.PlayerControl.ControlReq.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.ControlReq build() {
        frame.socket.common.proto.PlayerControl.ControlReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.ControlReq buildPartial() {
        frame.socket.common.proto.PlayerControl.ControlReq result = new frame.socket.common.proto.PlayerControl.ControlReq(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.common.proto.PlayerControl.ControlReq) {
          return mergeFrom((frame.socket.common.proto.PlayerControl.ControlReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.common.proto.PlayerControl.ControlReq other) {
        if (other == frame.socket.common.proto.PlayerControl.ControlReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.common.proto.PlayerControl.ControlReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.common.proto.PlayerControl.ControlReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game.ControlReq)
    }

    // @@protoc_insertion_point(class_scope:game.ControlReq)
    private static final frame.socket.common.proto.PlayerControl.ControlReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.common.proto.PlayerControl.ControlReq();
    }

    public static frame.socket.common.proto.PlayerControl.ControlReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlReq>
        PARSER = new com.google.protobuf.AbstractParser<ControlReq>() {
      @java.lang.Override
      public ControlReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.common.proto.PlayerControl.ControlReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControlResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.ControlRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *剩余输赢
     * </pre>
     *
     * <code>int32 leftWinLose = 2;</code>
     */
    int getLeftWinLose();
  }
  /**
   * <pre>
   * 600602  (后台查游戏DB实时输赢返回)
   * </pre>
   *
   * Protobuf type {@code game.ControlRes}
   */
  public  static final class ControlRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.ControlRes)
      ControlResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControlRes.newBuilder() to construct.
    private ControlRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlRes() {
      leftWinLose_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControlRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              leftWinLose_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_ControlRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_ControlRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.common.proto.PlayerControl.ControlRes.class, frame.socket.common.proto.PlayerControl.ControlRes.Builder.class);
    }

    public static final int LEFTWINLOSE_FIELD_NUMBER = 2;
    private int leftWinLose_;
    /**
     * <pre>
     *剩余输赢
     * </pre>
     *
     * <code>int32 leftWinLose = 2;</code>
     */
    public int getLeftWinLose() {
      return leftWinLose_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (leftWinLose_ != 0) {
        output.writeInt32(2, leftWinLose_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (leftWinLose_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, leftWinLose_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.common.proto.PlayerControl.ControlRes)) {
        return super.equals(obj);
      }
      frame.socket.common.proto.PlayerControl.ControlRes other = (frame.socket.common.proto.PlayerControl.ControlRes) obj;

      boolean result = true;
      result = result && (getLeftWinLose()
          == other.getLeftWinLose());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LEFTWINLOSE_FIELD_NUMBER;
      hash = (53 * hash) + getLeftWinLose();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.ControlRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.common.proto.PlayerControl.ControlRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 600602  (后台查游戏DB实时输赢返回)
     * </pre>
     *
     * Protobuf type {@code game.ControlRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.ControlRes)
        frame.socket.common.proto.PlayerControl.ControlResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_ControlRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_ControlRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.common.proto.PlayerControl.ControlRes.class, frame.socket.common.proto.PlayerControl.ControlRes.Builder.class);
      }

      // Construct using frame.socket.common.proto.PlayerControl.ControlRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        leftWinLose_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_ControlRes_descriptor;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.ControlRes getDefaultInstanceForType() {
        return frame.socket.common.proto.PlayerControl.ControlRes.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.ControlRes build() {
        frame.socket.common.proto.PlayerControl.ControlRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.ControlRes buildPartial() {
        frame.socket.common.proto.PlayerControl.ControlRes result = new frame.socket.common.proto.PlayerControl.ControlRes(this);
        result.leftWinLose_ = leftWinLose_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.common.proto.PlayerControl.ControlRes) {
          return mergeFrom((frame.socket.common.proto.PlayerControl.ControlRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.common.proto.PlayerControl.ControlRes other) {
        if (other == frame.socket.common.proto.PlayerControl.ControlRes.getDefaultInstance()) return this;
        if (other.getLeftWinLose() != 0) {
          setLeftWinLose(other.getLeftWinLose());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.common.proto.PlayerControl.ControlRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.common.proto.PlayerControl.ControlRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int leftWinLose_ ;
      /**
       * <pre>
       *剩余输赢
       * </pre>
       *
       * <code>int32 leftWinLose = 2;</code>
       */
      public int getLeftWinLose() {
        return leftWinLose_;
      }
      /**
       * <pre>
       *剩余输赢
       * </pre>
       *
       * <code>int32 leftWinLose = 2;</code>
       */
      public Builder setLeftWinLose(int value) {
        
        leftWinLose_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *剩余输赢
       * </pre>
       *
       * <code>int32 leftWinLose = 2;</code>
       */
      public Builder clearLeftWinLose() {
        
        leftWinLose_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game.ControlRes)
    }

    // @@protoc_insertion_point(class_scope:game.ControlRes)
    private static final frame.socket.common.proto.PlayerControl.ControlRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.common.proto.PlayerControl.ControlRes();
    }

    public static frame.socket.common.proto.PlayerControl.ControlRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlRes>
        PARSER = new com.google.protobuf.AbstractParser<ControlRes>() {
      @java.lang.Override
      public ControlRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.common.proto.PlayerControl.ControlRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateControlReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.UpdateControlReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *输赢
     * </pre>
     *
     * <code>int32 winLose = 1;</code>
     */
    int getWinLose();

    /**
     * <pre>
     *对战，下注类型输赢胜率
     * </pre>
     *
     * <code>int32 winRateBattleBet = 2;</code>
     */
    int getWinRateBattleBet();

    /**
     * <pre>
     *捕鱼类型输赢胜率
     * </pre>
     *
     * <code>int32 winRateFish = 3;</code>
     */
    int getWinRateFish();
  }
  /**
   * <pre>
   * 600603    删除600604
   * </pre>
   *
   * Protobuf type {@code game.UpdateControlReq}
   */
  public  static final class UpdateControlReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.UpdateControlReq)
      UpdateControlReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateControlReq.newBuilder() to construct.
    private UpdateControlReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateControlReq() {
      winLose_ = 0;
      winRateBattleBet_ = 0;
      winRateFish_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateControlReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              winLose_ = input.readInt32();
              break;
            }
            case 16: {

              winRateBattleBet_ = input.readInt32();
              break;
            }
            case 24: {

              winRateFish_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.common.proto.PlayerControl.UpdateControlReq.class, frame.socket.common.proto.PlayerControl.UpdateControlReq.Builder.class);
    }

    public static final int WINLOSE_FIELD_NUMBER = 1;
    private int winLose_;
    /**
     * <pre>
     *输赢
     * </pre>
     *
     * <code>int32 winLose = 1;</code>
     */
    public int getWinLose() {
      return winLose_;
    }

    public static final int WINRATEBATTLEBET_FIELD_NUMBER = 2;
    private int winRateBattleBet_;
    /**
     * <pre>
     *对战，下注类型输赢胜率
     * </pre>
     *
     * <code>int32 winRateBattleBet = 2;</code>
     */
    public int getWinRateBattleBet() {
      return winRateBattleBet_;
    }

    public static final int WINRATEFISH_FIELD_NUMBER = 3;
    private int winRateFish_;
    /**
     * <pre>
     *捕鱼类型输赢胜率
     * </pre>
     *
     * <code>int32 winRateFish = 3;</code>
     */
    public int getWinRateFish() {
      return winRateFish_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (winLose_ != 0) {
        output.writeInt32(1, winLose_);
      }
      if (winRateBattleBet_ != 0) {
        output.writeInt32(2, winRateBattleBet_);
      }
      if (winRateFish_ != 0) {
        output.writeInt32(3, winRateFish_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (winLose_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, winLose_);
      }
      if (winRateBattleBet_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, winRateBattleBet_);
      }
      if (winRateFish_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, winRateFish_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.common.proto.PlayerControl.UpdateControlReq)) {
        return super.equals(obj);
      }
      frame.socket.common.proto.PlayerControl.UpdateControlReq other = (frame.socket.common.proto.PlayerControl.UpdateControlReq) obj;

      boolean result = true;
      result = result && (getWinLose()
          == other.getWinLose());
      result = result && (getWinRateBattleBet()
          == other.getWinRateBattleBet());
      result = result && (getWinRateFish()
          == other.getWinRateFish());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WINLOSE_FIELD_NUMBER;
      hash = (53 * hash) + getWinLose();
      hash = (37 * hash) + WINRATEBATTLEBET_FIELD_NUMBER;
      hash = (53 * hash) + getWinRateBattleBet();
      hash = (37 * hash) + WINRATEFISH_FIELD_NUMBER;
      hash = (53 * hash) + getWinRateFish();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.common.proto.PlayerControl.UpdateControlReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 600603    删除600604
     * </pre>
     *
     * Protobuf type {@code game.UpdateControlReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.UpdateControlReq)
        frame.socket.common.proto.PlayerControl.UpdateControlReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.common.proto.PlayerControl.UpdateControlReq.class, frame.socket.common.proto.PlayerControl.UpdateControlReq.Builder.class);
      }

      // Construct using frame.socket.common.proto.PlayerControl.UpdateControlReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        winLose_ = 0;

        winRateBattleBet_ = 0;

        winRateFish_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlReq_descriptor;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlReq getDefaultInstanceForType() {
        return frame.socket.common.proto.PlayerControl.UpdateControlReq.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlReq build() {
        frame.socket.common.proto.PlayerControl.UpdateControlReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlReq buildPartial() {
        frame.socket.common.proto.PlayerControl.UpdateControlReq result = new frame.socket.common.proto.PlayerControl.UpdateControlReq(this);
        result.winLose_ = winLose_;
        result.winRateBattleBet_ = winRateBattleBet_;
        result.winRateFish_ = winRateFish_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.common.proto.PlayerControl.UpdateControlReq) {
          return mergeFrom((frame.socket.common.proto.PlayerControl.UpdateControlReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.common.proto.PlayerControl.UpdateControlReq other) {
        if (other == frame.socket.common.proto.PlayerControl.UpdateControlReq.getDefaultInstance()) return this;
        if (other.getWinLose() != 0) {
          setWinLose(other.getWinLose());
        }
        if (other.getWinRateBattleBet() != 0) {
          setWinRateBattleBet(other.getWinRateBattleBet());
        }
        if (other.getWinRateFish() != 0) {
          setWinRateFish(other.getWinRateFish());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.common.proto.PlayerControl.UpdateControlReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.common.proto.PlayerControl.UpdateControlReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int winLose_ ;
      /**
       * <pre>
       *输赢
       * </pre>
       *
       * <code>int32 winLose = 1;</code>
       */
      public int getWinLose() {
        return winLose_;
      }
      /**
       * <pre>
       *输赢
       * </pre>
       *
       * <code>int32 winLose = 1;</code>
       */
      public Builder setWinLose(int value) {
        
        winLose_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *输赢
       * </pre>
       *
       * <code>int32 winLose = 1;</code>
       */
      public Builder clearWinLose() {
        
        winLose_ = 0;
        onChanged();
        return this;
      }

      private int winRateBattleBet_ ;
      /**
       * <pre>
       *对战，下注类型输赢胜率
       * </pre>
       *
       * <code>int32 winRateBattleBet = 2;</code>
       */
      public int getWinRateBattleBet() {
        return winRateBattleBet_;
      }
      /**
       * <pre>
       *对战，下注类型输赢胜率
       * </pre>
       *
       * <code>int32 winRateBattleBet = 2;</code>
       */
      public Builder setWinRateBattleBet(int value) {
        
        winRateBattleBet_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对战，下注类型输赢胜率
       * </pre>
       *
       * <code>int32 winRateBattleBet = 2;</code>
       */
      public Builder clearWinRateBattleBet() {
        
        winRateBattleBet_ = 0;
        onChanged();
        return this;
      }

      private int winRateFish_ ;
      /**
       * <pre>
       *捕鱼类型输赢胜率
       * </pre>
       *
       * <code>int32 winRateFish = 3;</code>
       */
      public int getWinRateFish() {
        return winRateFish_;
      }
      /**
       * <pre>
       *捕鱼类型输赢胜率
       * </pre>
       *
       * <code>int32 winRateFish = 3;</code>
       */
      public Builder setWinRateFish(int value) {
        
        winRateFish_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *捕鱼类型输赢胜率
       * </pre>
       *
       * <code>int32 winRateFish = 3;</code>
       */
      public Builder clearWinRateFish() {
        
        winRateFish_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game.UpdateControlReq)
    }

    // @@protoc_insertion_point(class_scope:game.UpdateControlReq)
    private static final frame.socket.common.proto.PlayerControl.UpdateControlReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.common.proto.PlayerControl.UpdateControlReq();
    }

    public static frame.socket.common.proto.PlayerControl.UpdateControlReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateControlReq>
        PARSER = new com.google.protobuf.AbstractParser<UpdateControlReq>() {
      @java.lang.Override
      public UpdateControlReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateControlReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateControlReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateControlReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.common.proto.PlayerControl.UpdateControlReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateControlResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.UpdateControlRes)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 600604
   * </pre>
   *
   * Protobuf type {@code game.UpdateControlRes}
   */
  public  static final class UpdateControlRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.UpdateControlRes)
      UpdateControlResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateControlRes.newBuilder() to construct.
    private UpdateControlRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateControlRes() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateControlRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.common.proto.PlayerControl.UpdateControlRes.class, frame.socket.common.proto.PlayerControl.UpdateControlRes.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.common.proto.PlayerControl.UpdateControlRes)) {
        return super.equals(obj);
      }
      frame.socket.common.proto.PlayerControl.UpdateControlRes other = (frame.socket.common.proto.PlayerControl.UpdateControlRes) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.common.proto.PlayerControl.UpdateControlRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 600604
     * </pre>
     *
     * Protobuf type {@code game.UpdateControlRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.UpdateControlRes)
        frame.socket.common.proto.PlayerControl.UpdateControlResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.common.proto.PlayerControl.UpdateControlRes.class, frame.socket.common.proto.PlayerControl.UpdateControlRes.Builder.class);
      }

      // Construct using frame.socket.common.proto.PlayerControl.UpdateControlRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlRes_descriptor;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlRes getDefaultInstanceForType() {
        return frame.socket.common.proto.PlayerControl.UpdateControlRes.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlRes build() {
        frame.socket.common.proto.PlayerControl.UpdateControlRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlRes buildPartial() {
        frame.socket.common.proto.PlayerControl.UpdateControlRes result = new frame.socket.common.proto.PlayerControl.UpdateControlRes(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.common.proto.PlayerControl.UpdateControlRes) {
          return mergeFrom((frame.socket.common.proto.PlayerControl.UpdateControlRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.common.proto.PlayerControl.UpdateControlRes other) {
        if (other == frame.socket.common.proto.PlayerControl.UpdateControlRes.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.common.proto.PlayerControl.UpdateControlRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.common.proto.PlayerControl.UpdateControlRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game.UpdateControlRes)
    }

    // @@protoc_insertion_point(class_scope:game.UpdateControlRes)
    private static final frame.socket.common.proto.PlayerControl.UpdateControlRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.common.proto.PlayerControl.UpdateControlRes();
    }

    public static frame.socket.common.proto.PlayerControl.UpdateControlRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateControlRes>
        PARSER = new com.google.protobuf.AbstractParser<UpdateControlRes>() {
      @java.lang.Override
      public UpdateControlRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateControlRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateControlRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateControlRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.common.proto.PlayerControl.UpdateControlRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateControlPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.UpdateControlPlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <code>int32 leftWinLose = 2;</code>
     */
    int getLeftWinLose();
  }
  /**
   * <pre>
   * 游戏更新DB单控
   * </pre>
   *
   * Protobuf type {@code game.UpdateControlPlayer}
   */
  public  static final class UpdateControlPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.UpdateControlPlayer)
      UpdateControlPlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateControlPlayer.newBuilder() to construct.
    private UpdateControlPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateControlPlayer() {
      userId_ = 0;
      leftWinLose_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateControlPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 16: {

              leftWinLose_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlPlayer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.common.proto.PlayerControl.UpdateControlPlayer.class, frame.socket.common.proto.PlayerControl.UpdateControlPlayer.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int LEFTWINLOSE_FIELD_NUMBER = 2;
    private int leftWinLose_;
    /**
     * <code>int32 leftWinLose = 2;</code>
     */
    public int getLeftWinLose() {
      return leftWinLose_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (leftWinLose_ != 0) {
        output.writeInt32(2, leftWinLose_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (leftWinLose_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, leftWinLose_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.common.proto.PlayerControl.UpdateControlPlayer)) {
        return super.equals(obj);
      }
      frame.socket.common.proto.PlayerControl.UpdateControlPlayer other = (frame.socket.common.proto.PlayerControl.UpdateControlPlayer) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && (getLeftWinLose()
          == other.getLeftWinLose());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + LEFTWINLOSE_FIELD_NUMBER;
      hash = (53 * hash) + getLeftWinLose();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.common.proto.PlayerControl.UpdateControlPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 游戏更新DB单控
     * </pre>
     *
     * Protobuf type {@code game.UpdateControlPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.UpdateControlPlayer)
        frame.socket.common.proto.PlayerControl.UpdateControlPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlPlayer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.common.proto.PlayerControl.UpdateControlPlayer.class, frame.socket.common.proto.PlayerControl.UpdateControlPlayer.Builder.class);
      }

      // Construct using frame.socket.common.proto.PlayerControl.UpdateControlPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0;

        leftWinLose_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.common.proto.PlayerControl.internal_static_game_UpdateControlPlayer_descriptor;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlPlayer getDefaultInstanceForType() {
        return frame.socket.common.proto.PlayerControl.UpdateControlPlayer.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlPlayer build() {
        frame.socket.common.proto.PlayerControl.UpdateControlPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.common.proto.PlayerControl.UpdateControlPlayer buildPartial() {
        frame.socket.common.proto.PlayerControl.UpdateControlPlayer result = new frame.socket.common.proto.PlayerControl.UpdateControlPlayer(this);
        result.userId_ = userId_;
        result.leftWinLose_ = leftWinLose_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.common.proto.PlayerControl.UpdateControlPlayer) {
          return mergeFrom((frame.socket.common.proto.PlayerControl.UpdateControlPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.common.proto.PlayerControl.UpdateControlPlayer other) {
        if (other == frame.socket.common.proto.PlayerControl.UpdateControlPlayer.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getLeftWinLose() != 0) {
          setLeftWinLose(other.getLeftWinLose());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.common.proto.PlayerControl.UpdateControlPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.common.proto.PlayerControl.UpdateControlPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int leftWinLose_ ;
      /**
       * <code>int32 leftWinLose = 2;</code>
       */
      public int getLeftWinLose() {
        return leftWinLose_;
      }
      /**
       * <code>int32 leftWinLose = 2;</code>
       */
      public Builder setLeftWinLose(int value) {
        
        leftWinLose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leftWinLose = 2;</code>
       */
      public Builder clearLeftWinLose() {
        
        leftWinLose_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game.UpdateControlPlayer)
    }

    // @@protoc_insertion_point(class_scope:game.UpdateControlPlayer)
    private static final frame.socket.common.proto.PlayerControl.UpdateControlPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.common.proto.PlayerControl.UpdateControlPlayer();
    }

    public static frame.socket.common.proto.PlayerControl.UpdateControlPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateControlPlayer>
        PARSER = new com.google.protobuf.AbstractParser<UpdateControlPlayer>() {
      @java.lang.Override
      public UpdateControlPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateControlPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateControlPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateControlPlayer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.common.proto.PlayerControl.UpdateControlPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_ControlReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_ControlReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_ControlRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_ControlRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_UpdateControlReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_UpdateControlReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_UpdateControlRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_UpdateControlRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_UpdateControlPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_UpdateControlPlayer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030game/playerControl.proto\022\004game\"\014\n\nCont" +
      "rolReq\"!\n\nControlRes\022\023\n\013leftWinLose\030\002 \001(" +
      "\005\"R\n\020UpdateControlReq\022\017\n\007winLose\030\001 \001(\005\022\030" +
      "\n\020winRateBattleBet\030\002 \001(\005\022\023\n\013winRateFish\030" +
      "\003 \001(\005\"\022\n\020UpdateControlRes\":\n\023UpdateContr" +
      "olPlayer\022\016\n\006userId\030\001 \001(\005\022\023\n\013leftWinLose\030" +
      "\002 \001(\005B\033\n\031frame.socket.common.protob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_game_ControlReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_game_ControlReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_ControlReq_descriptor,
        new java.lang.String[] { });
    internal_static_game_ControlRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_game_ControlRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_ControlRes_descriptor,
        new java.lang.String[] { "LeftWinLose", });
    internal_static_game_UpdateControlReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_game_UpdateControlReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_UpdateControlReq_descriptor,
        new java.lang.String[] { "WinLose", "WinRateBattleBet", "WinRateFish", });
    internal_static_game_UpdateControlRes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_game_UpdateControlRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_UpdateControlRes_descriptor,
        new java.lang.String[] { });
    internal_static_game_UpdateControlPlayer_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_game_UpdateControlPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_UpdateControlPlayer_descriptor,
        new java.lang.String[] { "UserId", "LeftWinLose", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
