// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game/gameControl.proto

package frame.socket.game.proto;

public final class GameControl {
  private GameControl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BcbmLotteryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.BcbmLottery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 lottery = 1;</code>
     */
    int getLottery();
  }
  /**
   * <pre>
   *奔驰宝马
   * </pre>
   *
   * Protobuf type {@code game.BcbmLottery}
   */
  public  static final class BcbmLottery extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.BcbmLottery)
      BcbmLotteryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BcbmLottery.newBuilder() to construct.
    private BcbmLottery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BcbmLottery() {
      lottery_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BcbmLottery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              lottery_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.game.proto.GameControl.internal_static_game_BcbmLottery_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.game.proto.GameControl.internal_static_game_BcbmLottery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.game.proto.GameControl.BcbmLottery.class, frame.socket.game.proto.GameControl.BcbmLottery.Builder.class);
    }

    public static final int LOTTERY_FIELD_NUMBER = 1;
    private int lottery_;
    /**
     * <code>int32 lottery = 1;</code>
     */
    public int getLottery() {
      return lottery_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (lottery_ != 0) {
        output.writeInt32(1, lottery_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (lottery_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, lottery_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.game.proto.GameControl.BcbmLottery)) {
        return super.equals(obj);
      }
      frame.socket.game.proto.GameControl.BcbmLottery other = (frame.socket.game.proto.GameControl.BcbmLottery) obj;

      boolean result = true;
      result = result && (getLottery()
          == other.getLottery());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOTTERY_FIELD_NUMBER;
      hash = (53 * hash) + getLottery();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.game.proto.GameControl.BcbmLottery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.game.proto.GameControl.BcbmLottery prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *奔驰宝马
     * </pre>
     *
     * Protobuf type {@code game.BcbmLottery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.BcbmLottery)
        frame.socket.game.proto.GameControl.BcbmLotteryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.game.proto.GameControl.internal_static_game_BcbmLottery_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.game.proto.GameControl.internal_static_game_BcbmLottery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.game.proto.GameControl.BcbmLottery.class, frame.socket.game.proto.GameControl.BcbmLottery.Builder.class);
      }

      // Construct using frame.socket.game.proto.GameControl.BcbmLottery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        lottery_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.game.proto.GameControl.internal_static_game_BcbmLottery_descriptor;
      }

      @java.lang.Override
      public frame.socket.game.proto.GameControl.BcbmLottery getDefaultInstanceForType() {
        return frame.socket.game.proto.GameControl.BcbmLottery.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.game.proto.GameControl.BcbmLottery build() {
        frame.socket.game.proto.GameControl.BcbmLottery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.game.proto.GameControl.BcbmLottery buildPartial() {
        frame.socket.game.proto.GameControl.BcbmLottery result = new frame.socket.game.proto.GameControl.BcbmLottery(this);
        result.lottery_ = lottery_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.game.proto.GameControl.BcbmLottery) {
          return mergeFrom((frame.socket.game.proto.GameControl.BcbmLottery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.game.proto.GameControl.BcbmLottery other) {
        if (other == frame.socket.game.proto.GameControl.BcbmLottery.getDefaultInstance()) return this;
        if (other.getLottery() != 0) {
          setLottery(other.getLottery());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.game.proto.GameControl.BcbmLottery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.game.proto.GameControl.BcbmLottery) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int lottery_ ;
      /**
       * <code>int32 lottery = 1;</code>
       */
      public int getLottery() {
        return lottery_;
      }
      /**
       * <code>int32 lottery = 1;</code>
       */
      public Builder setLottery(int value) {
        
        lottery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 lottery = 1;</code>
       */
      public Builder clearLottery() {
        
        lottery_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game.BcbmLottery)
    }

    // @@protoc_insertion_point(class_scope:game.BcbmLottery)
    private static final frame.socket.game.proto.GameControl.BcbmLottery DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.game.proto.GameControl.BcbmLottery();
    }

    public static frame.socket.game.proto.GameControl.BcbmLottery getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BcbmLottery>
        PARSER = new com.google.protobuf.AbstractParser<BcbmLottery>() {
      @java.lang.Override
      public BcbmLottery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BcbmLottery(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BcbmLottery> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BcbmLottery> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.game.proto.GameControl.BcbmLottery getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControlReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:game.ControlReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.game.BcbmLottery bcbm = 1;</code>
     */
    boolean hasBcbm();
    /**
     * <code>.game.BcbmLottery bcbm = 1;</code>
     */
    frame.socket.game.proto.GameControl.BcbmLottery getBcbm();
    /**
     * <code>.game.BcbmLottery bcbm = 1;</code>
     */
    frame.socket.game.proto.GameControl.BcbmLotteryOrBuilder getBcbmOrBuilder();
  }
  /**
   * <pre>
   *控制请求 //600901
   * </pre>
   *
   * Protobuf type {@code game.ControlReq}
   */
  public  static final class ControlReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:game.ControlReq)
      ControlReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ControlReq.newBuilder() to construct.
    private ControlReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ControlReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              frame.socket.game.proto.GameControl.BcbmLottery.Builder subBuilder = null;
              if (bcbm_ != null) {
                subBuilder = bcbm_.toBuilder();
              }
              bcbm_ = input.readMessage(frame.socket.game.proto.GameControl.BcbmLottery.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bcbm_);
                bcbm_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.game.proto.GameControl.internal_static_game_ControlReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.game.proto.GameControl.internal_static_game_ControlReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.game.proto.GameControl.ControlReq.class, frame.socket.game.proto.GameControl.ControlReq.Builder.class);
    }

    public static final int BCBM_FIELD_NUMBER = 1;
    private frame.socket.game.proto.GameControl.BcbmLottery bcbm_;
    /**
     * <code>.game.BcbmLottery bcbm = 1;</code>
     */
    public boolean hasBcbm() {
      return bcbm_ != null;
    }
    /**
     * <code>.game.BcbmLottery bcbm = 1;</code>
     */
    public frame.socket.game.proto.GameControl.BcbmLottery getBcbm() {
      return bcbm_ == null ? frame.socket.game.proto.GameControl.BcbmLottery.getDefaultInstance() : bcbm_;
    }
    /**
     * <code>.game.BcbmLottery bcbm = 1;</code>
     */
    public frame.socket.game.proto.GameControl.BcbmLotteryOrBuilder getBcbmOrBuilder() {
      return getBcbm();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bcbm_ != null) {
        output.writeMessage(1, getBcbm());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bcbm_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBcbm());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.game.proto.GameControl.ControlReq)) {
        return super.equals(obj);
      }
      frame.socket.game.proto.GameControl.ControlReq other = (frame.socket.game.proto.GameControl.ControlReq) obj;

      boolean result = true;
      result = result && (hasBcbm() == other.hasBcbm());
      if (hasBcbm()) {
        result = result && getBcbm()
            .equals(other.getBcbm());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBcbm()) {
        hash = (37 * hash) + BCBM_FIELD_NUMBER;
        hash = (53 * hash) + getBcbm().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.game.proto.GameControl.ControlReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.game.proto.GameControl.ControlReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *控制请求 //600901
     * </pre>
     *
     * Protobuf type {@code game.ControlReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:game.ControlReq)
        frame.socket.game.proto.GameControl.ControlReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.game.proto.GameControl.internal_static_game_ControlReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.game.proto.GameControl.internal_static_game_ControlReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.game.proto.GameControl.ControlReq.class, frame.socket.game.proto.GameControl.ControlReq.Builder.class);
      }

      // Construct using frame.socket.game.proto.GameControl.ControlReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (bcbmBuilder_ == null) {
          bcbm_ = null;
        } else {
          bcbm_ = null;
          bcbmBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.game.proto.GameControl.internal_static_game_ControlReq_descriptor;
      }

      @java.lang.Override
      public frame.socket.game.proto.GameControl.ControlReq getDefaultInstanceForType() {
        return frame.socket.game.proto.GameControl.ControlReq.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.game.proto.GameControl.ControlReq build() {
        frame.socket.game.proto.GameControl.ControlReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.game.proto.GameControl.ControlReq buildPartial() {
        frame.socket.game.proto.GameControl.ControlReq result = new frame.socket.game.proto.GameControl.ControlReq(this);
        if (bcbmBuilder_ == null) {
          result.bcbm_ = bcbm_;
        } else {
          result.bcbm_ = bcbmBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.game.proto.GameControl.ControlReq) {
          return mergeFrom((frame.socket.game.proto.GameControl.ControlReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.game.proto.GameControl.ControlReq other) {
        if (other == frame.socket.game.proto.GameControl.ControlReq.getDefaultInstance()) return this;
        if (other.hasBcbm()) {
          mergeBcbm(other.getBcbm());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.game.proto.GameControl.ControlReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.game.proto.GameControl.ControlReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private frame.socket.game.proto.GameControl.BcbmLottery bcbm_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          frame.socket.game.proto.GameControl.BcbmLottery, frame.socket.game.proto.GameControl.BcbmLottery.Builder, frame.socket.game.proto.GameControl.BcbmLotteryOrBuilder> bcbmBuilder_;
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public boolean hasBcbm() {
        return bcbmBuilder_ != null || bcbm_ != null;
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public frame.socket.game.proto.GameControl.BcbmLottery getBcbm() {
        if (bcbmBuilder_ == null) {
          return bcbm_ == null ? frame.socket.game.proto.GameControl.BcbmLottery.getDefaultInstance() : bcbm_;
        } else {
          return bcbmBuilder_.getMessage();
        }
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public Builder setBcbm(frame.socket.game.proto.GameControl.BcbmLottery value) {
        if (bcbmBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bcbm_ = value;
          onChanged();
        } else {
          bcbmBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public Builder setBcbm(
          frame.socket.game.proto.GameControl.BcbmLottery.Builder builderForValue) {
        if (bcbmBuilder_ == null) {
          bcbm_ = builderForValue.build();
          onChanged();
        } else {
          bcbmBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public Builder mergeBcbm(frame.socket.game.proto.GameControl.BcbmLottery value) {
        if (bcbmBuilder_ == null) {
          if (bcbm_ != null) {
            bcbm_ =
              frame.socket.game.proto.GameControl.BcbmLottery.newBuilder(bcbm_).mergeFrom(value).buildPartial();
          } else {
            bcbm_ = value;
          }
          onChanged();
        } else {
          bcbmBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public Builder clearBcbm() {
        if (bcbmBuilder_ == null) {
          bcbm_ = null;
          onChanged();
        } else {
          bcbm_ = null;
          bcbmBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public frame.socket.game.proto.GameControl.BcbmLottery.Builder getBcbmBuilder() {
        
        onChanged();
        return getBcbmFieldBuilder().getBuilder();
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      public frame.socket.game.proto.GameControl.BcbmLotteryOrBuilder getBcbmOrBuilder() {
        if (bcbmBuilder_ != null) {
          return bcbmBuilder_.getMessageOrBuilder();
        } else {
          return bcbm_ == null ?
              frame.socket.game.proto.GameControl.BcbmLottery.getDefaultInstance() : bcbm_;
        }
      }
      /**
       * <code>.game.BcbmLottery bcbm = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          frame.socket.game.proto.GameControl.BcbmLottery, frame.socket.game.proto.GameControl.BcbmLottery.Builder, frame.socket.game.proto.GameControl.BcbmLotteryOrBuilder> 
          getBcbmFieldBuilder() {
        if (bcbmBuilder_ == null) {
          bcbmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              frame.socket.game.proto.GameControl.BcbmLottery, frame.socket.game.proto.GameControl.BcbmLottery.Builder, frame.socket.game.proto.GameControl.BcbmLotteryOrBuilder>(
                  getBcbm(),
                  getParentForChildren(),
                  isClean());
          bcbm_ = null;
        }
        return bcbmBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:game.ControlReq)
    }

    // @@protoc_insertion_point(class_scope:game.ControlReq)
    private static final frame.socket.game.proto.GameControl.ControlReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.game.proto.GameControl.ControlReq();
    }

    public static frame.socket.game.proto.GameControl.ControlReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlReq>
        PARSER = new com.google.protobuf.AbstractParser<ControlReq>() {
      @java.lang.Override
      public ControlReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ControlReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.game.proto.GameControl.ControlReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_BcbmLottery_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_BcbmLottery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_game_ControlReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_game_ControlReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026game/gameControl.proto\022\004game\"\036\n\013BcbmLo" +
      "ttery\022\017\n\007lottery\030\001 \001(\005\"-\n\nControlReq\022\037\n\004" +
      "bcbm\030\001 \001(\0132\021.game.BcbmLotteryB\031\n\027frame.s" +
      "ocket.game.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_game_BcbmLottery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_game_BcbmLottery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_BcbmLottery_descriptor,
        new java.lang.String[] { "Lottery", });
    internal_static_game_ControlReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_game_ControlReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_game_ControlReq_descriptor,
        new java.lang.String[] { "Bcbm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
