// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global/config.proto

package frame.socket.global.proto;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:global.ServerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string ip = 2;</code>
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>int32 port = 3;</code>
     */
    int getPort();

    /**
     * <code>.common.Server_Type type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>.common.Server_Type type = 4;</code>
     */
    frame.socket.common.proto.Type.Server_Type getType();

    /**
     * <code>int32 subType = 5;</code>
     */
    int getSubType();
  }
  /**
   * Protobuf type {@code global.ServerInfo}
   */
  public  static final class ServerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:global.ServerInfo)
      ServerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerInfo.newBuilder() to construct.
    private ServerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerInfo() {
      id_ = 0;
      ip_ = "";
      port_ = 0;
      type_ = 0;
      subType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 24: {

              port_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 40: {

              subType_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.global.proto.Config.internal_static_global_ServerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.global.proto.Config.internal_static_global_ServerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.global.proto.Config.ServerInfo.class, frame.socket.global.proto.Config.ServerInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 2;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private int port_;
    /**
     * <code>int32 port = 3;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>.common.Server_Type type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.common.Server_Type type = 4;</code>
     */
    public frame.socket.common.proto.Type.Server_Type getType() {
      @SuppressWarnings("deprecation")
      frame.socket.common.proto.Type.Server_Type result = frame.socket.common.proto.Type.Server_Type.valueOf(type_);
      return result == null ? frame.socket.common.proto.Type.Server_Type.UNRECOGNIZED : result;
    }

    public static final int SUBTYPE_FIELD_NUMBER = 5;
    private int subType_;
    /**
     * <code>int32 subType = 5;</code>
     */
    public int getSubType() {
      return subType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      if (port_ != 0) {
        output.writeInt32(3, port_);
      }
      if (type_ != frame.socket.common.proto.Type.Server_Type.SERVER_TYPE_GATE.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (subType_ != 0) {
        output.writeInt32(5, subType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, port_);
      }
      if (type_ != frame.socket.common.proto.Type.Server_Type.SERVER_TYPE_GATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (subType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, subType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.global.proto.Config.ServerInfo)) {
        return super.equals(obj);
      }
      frame.socket.global.proto.Config.ServerInfo other = (frame.socket.global.proto.Config.ServerInfo) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getIp()
          .equals(other.getIp());
      result = result && (getPort()
          == other.getPort());
      result = result && type_ == other.type_;
      result = result && (getSubType()
          == other.getSubType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSubType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.ServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.global.proto.Config.ServerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code global.ServerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:global.ServerInfo)
        frame.socket.global.proto.Config.ServerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.global.proto.Config.internal_static_global_ServerInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.global.proto.Config.internal_static_global_ServerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.global.proto.Config.ServerInfo.class, frame.socket.global.proto.Config.ServerInfo.Builder.class);
      }

      // Construct using frame.socket.global.proto.Config.ServerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        ip_ = "";

        port_ = 0;

        type_ = 0;

        subType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.global.proto.Config.internal_static_global_ServerInfo_descriptor;
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.ServerInfo getDefaultInstanceForType() {
        return frame.socket.global.proto.Config.ServerInfo.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.ServerInfo build() {
        frame.socket.global.proto.Config.ServerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.ServerInfo buildPartial() {
        frame.socket.global.proto.Config.ServerInfo result = new frame.socket.global.proto.Config.ServerInfo(this);
        result.id_ = id_;
        result.ip_ = ip_;
        result.port_ = port_;
        result.type_ = type_;
        result.subType_ = subType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.global.proto.Config.ServerInfo) {
          return mergeFrom((frame.socket.global.proto.Config.ServerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.global.proto.Config.ServerInfo other) {
        if (other == frame.socket.global.proto.Config.ServerInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSubType() != 0) {
          setSubType(other.getSubType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.global.proto.Config.ServerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.global.proto.Config.ServerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 2;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 3;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 3;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.common.Server_Type type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.common.Server_Type type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.common.Server_Type type = 4;</code>
       */
      public frame.socket.common.proto.Type.Server_Type getType() {
        @SuppressWarnings("deprecation")
        frame.socket.common.proto.Type.Server_Type result = frame.socket.common.proto.Type.Server_Type.valueOf(type_);
        return result == null ? frame.socket.common.proto.Type.Server_Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.common.Server_Type type = 4;</code>
       */
      public Builder setType(frame.socket.common.proto.Type.Server_Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.common.Server_Type type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int subType_ ;
      /**
       * <code>int32 subType = 5;</code>
       */
      public int getSubType() {
        return subType_;
      }
      /**
       * <code>int32 subType = 5;</code>
       */
      public Builder setSubType(int value) {
        
        subType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 subType = 5;</code>
       */
      public Builder clearSubType() {
        
        subType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:global.ServerInfo)
    }

    // @@protoc_insertion_point(class_scope:global.ServerInfo)
    private static final frame.socket.global.proto.Config.ServerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.global.proto.Config.ServerInfo();
    }

    public static frame.socket.global.proto.Config.ServerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerInfo>
        PARSER = new com.google.protobuf.AbstractParser<ServerInfo>() {
      @java.lang.Override
      public ServerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.global.proto.Config.ServerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetServerListA2C_ROrBuilder extends
      // @@protoc_insertion_point(interface_extends:global.GetServerListA2C_R)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * 获取服务器列表
   * 504001
   * </pre>
   *
   * Protobuf type {@code global.GetServerListA2C_R}
   */
  public  static final class GetServerListA2C_R extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:global.GetServerListA2C_R)
      GetServerListA2C_ROrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetServerListA2C_R.newBuilder() to construct.
    private GetServerListA2C_R(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetServerListA2C_R() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetServerListA2C_R(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.global.proto.Config.internal_static_global_GetServerListA2C_R_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.global.proto.Config.internal_static_global_GetServerListA2C_R_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.global.proto.Config.GetServerListA2C_R.class, frame.socket.global.proto.Config.GetServerListA2C_R.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.global.proto.Config.GetServerListA2C_R)) {
        return super.equals(obj);
      }
      frame.socket.global.proto.Config.GetServerListA2C_R other = (frame.socket.global.proto.Config.GetServerListA2C_R) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.GetServerListA2C_R parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.global.proto.Config.GetServerListA2C_R prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 获取服务器列表
     * 504001
     * </pre>
     *
     * Protobuf type {@code global.GetServerListA2C_R}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:global.GetServerListA2C_R)
        frame.socket.global.proto.Config.GetServerListA2C_ROrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.global.proto.Config.internal_static_global_GetServerListA2C_R_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.global.proto.Config.internal_static_global_GetServerListA2C_R_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.global.proto.Config.GetServerListA2C_R.class, frame.socket.global.proto.Config.GetServerListA2C_R.Builder.class);
      }

      // Construct using frame.socket.global.proto.Config.GetServerListA2C_R.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.global.proto.Config.internal_static_global_GetServerListA2C_R_descriptor;
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.GetServerListA2C_R getDefaultInstanceForType() {
        return frame.socket.global.proto.Config.GetServerListA2C_R.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.GetServerListA2C_R build() {
        frame.socket.global.proto.Config.GetServerListA2C_R result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.GetServerListA2C_R buildPartial() {
        frame.socket.global.proto.Config.GetServerListA2C_R result = new frame.socket.global.proto.Config.GetServerListA2C_R(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.global.proto.Config.GetServerListA2C_R) {
          return mergeFrom((frame.socket.global.proto.Config.GetServerListA2C_R)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.global.proto.Config.GetServerListA2C_R other) {
        if (other == frame.socket.global.proto.Config.GetServerListA2C_R.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.global.proto.Config.GetServerListA2C_R parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.global.proto.Config.GetServerListA2C_R) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:global.GetServerListA2C_R)
    }

    // @@protoc_insertion_point(class_scope:global.GetServerListA2C_R)
    private static final frame.socket.global.proto.Config.GetServerListA2C_R DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.global.proto.Config.GetServerListA2C_R();
    }

    public static frame.socket.global.proto.Config.GetServerListA2C_R getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetServerListA2C_R>
        PARSER = new com.google.protobuf.AbstractParser<GetServerListA2C_R>() {
      @java.lang.Override
      public GetServerListA2C_R parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetServerListA2C_R(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetServerListA2C_R> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetServerListA2C_R> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.global.proto.Config.GetServerListA2C_R getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetServerListC2A_SOrBuilder extends
      // @@protoc_insertion_point(interface_extends:global.GetServerListC2A_S)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    java.util.List<frame.socket.global.proto.Config.ServerInfo> 
        getInfoList();
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    frame.socket.global.proto.Config.ServerInfo getInfo(int index);
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    int getInfoCount();
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    java.util.List<? extends frame.socket.global.proto.Config.ServerInfoOrBuilder> 
        getInfoOrBuilderList();
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    frame.socket.global.proto.Config.ServerInfoOrBuilder getInfoOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 504002
   * </pre>
   *
   * Protobuf type {@code global.GetServerListC2A_S}
   */
  public  static final class GetServerListC2A_S extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:global.GetServerListC2A_S)
      GetServerListC2A_SOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetServerListC2A_S.newBuilder() to construct.
    private GetServerListC2A_S(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetServerListC2A_S() {
      info_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetServerListC2A_S(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                info_ = new java.util.ArrayList<frame.socket.global.proto.Config.ServerInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              info_.add(
                  input.readMessage(frame.socket.global.proto.Config.ServerInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = java.util.Collections.unmodifiableList(info_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return frame.socket.global.proto.Config.internal_static_global_GetServerListC2A_S_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return frame.socket.global.proto.Config.internal_static_global_GetServerListC2A_S_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              frame.socket.global.proto.Config.GetServerListC2A_S.class, frame.socket.global.proto.Config.GetServerListC2A_S.Builder.class);
    }

    public static final int INFO_FIELD_NUMBER = 1;
    private java.util.List<frame.socket.global.proto.Config.ServerInfo> info_;
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    public java.util.List<frame.socket.global.proto.Config.ServerInfo> getInfoList() {
      return info_;
    }
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    public java.util.List<? extends frame.socket.global.proto.Config.ServerInfoOrBuilder> 
        getInfoOrBuilderList() {
      return info_;
    }
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    public int getInfoCount() {
      return info_.size();
    }
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    public frame.socket.global.proto.Config.ServerInfo getInfo(int index) {
      return info_.get(index);
    }
    /**
     * <code>repeated .global.ServerInfo info = 1;</code>
     */
    public frame.socket.global.proto.Config.ServerInfoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(1, info_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof frame.socket.global.proto.Config.GetServerListC2A_S)) {
        return super.equals(obj);
      }
      frame.socket.global.proto.Config.GetServerListC2A_S other = (frame.socket.global.proto.Config.GetServerListC2A_S) obj;

      boolean result = true;
      result = result && getInfoList()
          .equals(other.getInfoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInfoCount() > 0) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static frame.socket.global.proto.Config.GetServerListC2A_S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(frame.socket.global.proto.Config.GetServerListC2A_S prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 504002
     * </pre>
     *
     * Protobuf type {@code global.GetServerListC2A_S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:global.GetServerListC2A_S)
        frame.socket.global.proto.Config.GetServerListC2A_SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return frame.socket.global.proto.Config.internal_static_global_GetServerListC2A_S_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return frame.socket.global.proto.Config.internal_static_global_GetServerListC2A_S_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                frame.socket.global.proto.Config.GetServerListC2A_S.class, frame.socket.global.proto.Config.GetServerListC2A_S.Builder.class);
      }

      // Construct using frame.socket.global.proto.Config.GetServerListC2A_S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return frame.socket.global.proto.Config.internal_static_global_GetServerListC2A_S_descriptor;
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.GetServerListC2A_S getDefaultInstanceForType() {
        return frame.socket.global.proto.Config.GetServerListC2A_S.getDefaultInstance();
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.GetServerListC2A_S build() {
        frame.socket.global.proto.Config.GetServerListC2A_S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public frame.socket.global.proto.Config.GetServerListC2A_S buildPartial() {
        frame.socket.global.proto.Config.GetServerListC2A_S result = new frame.socket.global.proto.Config.GetServerListC2A_S(this);
        int from_bitField0_ = bitField0_;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof frame.socket.global.proto.Config.GetServerListC2A_S) {
          return mergeFrom((frame.socket.global.proto.Config.GetServerListC2A_S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(frame.socket.global.proto.Config.GetServerListC2A_S other) {
        if (other == frame.socket.global.proto.Config.GetServerListC2A_S.getDefaultInstance()) return this;
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        frame.socket.global.proto.Config.GetServerListC2A_S parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (frame.socket.global.proto.Config.GetServerListC2A_S) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<frame.socket.global.proto.Config.ServerInfo> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = new java.util.ArrayList<frame.socket.global.proto.Config.ServerInfo>(info_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          frame.socket.global.proto.Config.ServerInfo, frame.socket.global.proto.Config.ServerInfo.Builder, frame.socket.global.proto.Config.ServerInfoOrBuilder> infoBuilder_;

      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public java.util.List<frame.socket.global.proto.Config.ServerInfo> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public frame.socket.global.proto.Config.ServerInfo getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder setInfo(
          int index, frame.socket.global.proto.Config.ServerInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder setInfo(
          int index, frame.socket.global.proto.Config.ServerInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder addInfo(frame.socket.global.proto.Config.ServerInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder addInfo(
          int index, frame.socket.global.proto.Config.ServerInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder addInfo(
          frame.socket.global.proto.Config.ServerInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder addInfo(
          int index, frame.socket.global.proto.Config.ServerInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder addAllInfo(
          java.lang.Iterable<? extends frame.socket.global.proto.Config.ServerInfo> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public frame.socket.global.proto.Config.ServerInfo.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public frame.socket.global.proto.Config.ServerInfoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public java.util.List<? extends frame.socket.global.proto.Config.ServerInfoOrBuilder> 
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public frame.socket.global.proto.Config.ServerInfo.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            frame.socket.global.proto.Config.ServerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public frame.socket.global.proto.Config.ServerInfo.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, frame.socket.global.proto.Config.ServerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .global.ServerInfo info = 1;</code>
       */
      public java.util.List<frame.socket.global.proto.Config.ServerInfo.Builder> 
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          frame.socket.global.proto.Config.ServerInfo, frame.socket.global.proto.Config.ServerInfo.Builder, frame.socket.global.proto.Config.ServerInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              frame.socket.global.proto.Config.ServerInfo, frame.socket.global.proto.Config.ServerInfo.Builder, frame.socket.global.proto.Config.ServerInfoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:global.GetServerListC2A_S)
    }

    // @@protoc_insertion_point(class_scope:global.GetServerListC2A_S)
    private static final frame.socket.global.proto.Config.GetServerListC2A_S DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new frame.socket.global.proto.Config.GetServerListC2A_S();
    }

    public static frame.socket.global.proto.Config.GetServerListC2A_S getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetServerListC2A_S>
        PARSER = new com.google.protobuf.AbstractParser<GetServerListC2A_S>() {
      @java.lang.Override
      public GetServerListC2A_S parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetServerListC2A_S(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetServerListC2A_S> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetServerListC2A_S> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public frame.socket.global.proto.Config.GetServerListC2A_S getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_global_ServerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_global_ServerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_global_GetServerListA2C_R_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_global_GetServerListA2C_R_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_global_GetServerListC2A_S_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_global_GetServerListC2A_S_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023global/config.proto\022\006global\032\021common/ty" +
      "pe.proto\"f\n\nServerInfo\022\n\n\002id\030\001 \001(\005\022\n\n\002ip" +
      "\030\002 \001(\t\022\014\n\004port\030\003 \001(\005\022!\n\004type\030\004 \001(\0162\023.com" +
      "mon.Server_Type\022\017\n\007subType\030\005 \001(\005\"\024\n\022GetS" +
      "erverListA2C_R\"6\n\022GetServerListC2A_S\022 \n\004" +
      "info\030\001 \003(\0132\022.global.ServerInfoB\036\n\031frame." +
      "socket.global.proto\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          frame.socket.common.proto.Type.getDescriptor(),
        }, assigner);
    internal_static_global_ServerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_global_ServerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_global_ServerInfo_descriptor,
        new java.lang.String[] { "Id", "Ip", "Port", "Type", "SubType", });
    internal_static_global_GetServerListA2C_R_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_global_GetServerListA2C_R_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_global_GetServerListA2C_R_descriptor,
        new java.lang.String[] { });
    internal_static_global_GetServerListC2A_S_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_global_GetServerListC2A_S_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_global_GetServerListC2A_S_descriptor,
        new java.lang.String[] { "Info", });
    frame.socket.common.proto.Type.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
